// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'features/messages/data/models/conversation_model.dart';
import 'features/messages/data/models/message_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5375341815841322001),
    name: 'MessageEntity',
    lastPropertyId: const obx_int.IdUid(10, 9166843586932850203),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3006474307854842634),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8165948152748014068),
        name: 'conversationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 4008079769228058365),
        relationField: 'conversation',
        relationTarget: 'ConversationEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9067204639004792599),
        name: 'sender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5439868920763066878),
        name: 'recipient',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9080969374413075957),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9009236058258366457),
        name: 'direction',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1026230646187495696),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5357646845254933570),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1700968946644753393),
        name: 'deliveredAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9166843586932850203),
        name: 'readAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1455543976099056088),
    name: 'ConversationEntity',
    lastPropertyId: const obx_int.IdUid(5, 1055640043795711125),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6836525194538870540),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6798946987161807651),
        name: 'phoneNumber',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 8359516727592523395),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6872583965061551504),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1055640043795711125),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'MessageEntity',
        srcField: 'conversation',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 6250778339977439467),
    lastIndexId: const obx_int.IdUid(10, 6406851879587627698),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      4250335910603406057,
      1436577373895574948,
      3182602011264922967,
      6638233595618408220,
      5459571457470134927,
      2395211171204351679,
      3995295772271573276,
      6250778339977439467,
    ],
    retiredIndexUids: const [3991372056654495073, 1694544816209281144],
    retiredPropertyUids: const [
      5679657336757100110,
      1279866049208100900,
      697748146117681768,
      7394334120040501467,
      270094360314078890,
      56471255015703617,
      6066107697361515247,
      3386651742891778676,
      422900913002173774,
      3043204840579548016,
      4734420056265220583,
      2421627751045956915,
      5656086667509678572,
      92799455988394177,
      663571727081435749,
      6889954739208695501,
      4330536162377368616,
      8862452873405059297,
      1782978648055911808,
      6109432217419268787,
      4226479632194968684,
      4531194926739593728,
      5402093149626593501,
      3285525861187869163,
      7964634578740086654,
      4430145852122994316,
      2271710801886035932,
      2683824147592964566,
      6397993971426153014,
      8767888631018900982,
      1147526950891109038,
      155954423623942847,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MessageEntity: obx_int.EntityDefinition<MessageEntity>(
      model: _entities[0],
      toOneRelations: (MessageEntity object) => [object.conversation],
      toManyRelations: (MessageEntity object) => {},
      getId: (MessageEntity object) => object.id,
      setId: (MessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MessageEntity object, fb.Builder fbb) {
        final senderOffset = fbb.writeString(object.sender);
        final recipientOffset = fbb.writeString(object.recipient);
        final bodyOffset = fbb.writeString(object.body);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.conversation.targetId);
        fbb.addOffset(2, senderOffset);
        fbb.addOffset(3, recipientOffset);
        fbb.addOffset(4, bodyOffset);
        fbb.addInt64(5, object.direction);
        fbb.addInt64(6, object.status);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.deliveredAt?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.readAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final deliveredAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final readAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final senderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final recipientParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final directionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final deliveredAtParam = deliveredAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(deliveredAtValue);
        final readAtParam = readAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(readAtValue);
        final object = MessageEntity(
          sender: senderParam,
          recipient: recipientParam,
          body: bodyParam,
          direction: directionParam,
          status: statusParam,
          createdAt: createdAtParam,
          deliveredAt: deliveredAtParam,
          readAt: readAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.conversation.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.conversation.attach(store);
        return object;
      },
    ),
    ConversationEntity: obx_int.EntityDefinition<ConversationEntity>(
      model: _entities[1],
      toOneRelations: (ConversationEntity object) => [],
      toManyRelations: (ConversationEntity object) => {
        obx_int.RelInfo<MessageEntity>.toOneBacklink(
          2,
          object.id,
          (MessageEntity srcObject) => srcObject.conversation,
        ): object.messages,
      },
      getId: (ConversationEntity object) => object.id,
      setId: (ConversationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ConversationEntity object, fb.Builder fbb) {
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, phoneNumberOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = ConversationEntity(
          phoneNumber: phoneNumberParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ConversationEntity>(
          object.messages,
          store,
          obx_int.RelInfo<MessageEntity>.toOneBacklink(
            2,
            object.id,
            (MessageEntity srcObject) => srcObject.conversation,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MessageEntity] entity fields to define ObjectBox queries.
class MessageEntity_ {
  /// See [MessageEntity.id].
  static final id = obx.QueryIntegerProperty<MessageEntity>(
    _entities[0].properties[0],
  );

  /// See [MessageEntity.conversation].
  static final conversation =
      obx.QueryRelationToOne<MessageEntity, ConversationEntity>(
        _entities[0].properties[1],
      );

  /// See [MessageEntity.sender].
  static final sender = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[2],
  );

  /// See [MessageEntity.recipient].
  static final recipient = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[3],
  );

  /// See [MessageEntity.body].
  static final body = obx.QueryStringProperty<MessageEntity>(
    _entities[0].properties[4],
  );

  /// See [MessageEntity.direction].
  static final direction = obx.QueryIntegerProperty<MessageEntity>(
    _entities[0].properties[5],
  );

  /// See [MessageEntity.status].
  static final status = obx.QueryIntegerProperty<MessageEntity>(
    _entities[0].properties[6],
  );

  /// See [MessageEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MessageEntity>(
    _entities[0].properties[7],
  );

  /// See [MessageEntity.deliveredAt].
  static final deliveredAt = obx.QueryDateProperty<MessageEntity>(
    _entities[0].properties[8],
  );

  /// See [MessageEntity.readAt].
  static final readAt = obx.QueryDateProperty<MessageEntity>(
    _entities[0].properties[9],
  );
}

/// [ConversationEntity] entity fields to define ObjectBox queries.
class ConversationEntity_ {
  /// See [ConversationEntity.id].
  static final id = obx.QueryIntegerProperty<ConversationEntity>(
    _entities[1].properties[0],
  );

  /// See [ConversationEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<ConversationEntity>(
    _entities[1].properties[1],
  );

  /// See [ConversationEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ConversationEntity>(
    _entities[1].properties[2],
  );

  /// See [ConversationEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ConversationEntity>(
    _entities[1].properties[3],
  );

  /// see [ConversationEntity.messages]
  static final messages =
      obx.QueryBacklinkToMany<MessageEntity, ConversationEntity>(
        MessageEntity_.conversation,
      );
}
